# Generated by Django 5.2.5 on 2026-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_savingsplan_savingsdeposit_savingswithdrawal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsplan',
            old_name='deposit_amount',
            new_name='amount_per_deposit',
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Number of days/weeks/months/years depending on frequency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingsplan',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
