# Generated by Django 5.2.5 on 2026-07-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_rename_deposit_amount_savingsplan_amount_per_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='first_deposit_taken',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='savingsplan',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='savingsplan',
            name='status',
            field=models.CharField(),
        ),
    ]
