# Generated by Django 5.2.5 on 2026-07-05 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_remove_savingsplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsplan',
            name='auto_save',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='first_deposit_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='last_auto_save',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='next_auto_save',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsplan',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingsplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
