# Generated by Django 5.2.5 on 2026-07-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_savingsplan_auto_save_savingsplan_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingswithdrawal',
            name='plan',
        ),
        migrations.DeleteModel(
            name='SavingsDeposit',
        ),
        migrations.DeleteModel(
            name='SavingsWithdrawal',
        ),
    ]
