# Generated by Django 5.2.5 on 2026-08-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic name', max_length=50),
        ),
    ]
