BANKS = [
    {"code": "044", "name": "Access Bank"},
    {"code": "014", "name": "Afribank"},
    {"code": "050", "name": "Ecobank"},
    {"code": "011", "name": "First Bank"},
    {"code": "214", "name": "First City Monument Bank"},
    {"code": "070", "name": "Fidelity Bank"},
    {"code": "058", "name": "Guaranty Trust Bank"},
    {"code": "030", "name": "Heritage Bank"},
    {"code": "082", "name": "Keystone Bank"},
    {"code": "076", "name": "Polaris Bank"},
    {"code": "101", "name": "Providus Bank"},
    {"code": "221", "name": "Stanbic IBTC Bank"},
    {"code": "068", "name": "Standard Chartered Bank"},
    {"code": "232", "name": "Sterling Bank"},
    {"code": "100", "name": "SunTrust Bank"},
    {"code": "032", "name": "Union Bank"},
    {"code": "033", "name": "United Bank for Africa"},
    {"code": "215", "name": "Unity Bank"},
    {"code": "035", "name": "Wema Bank"},
    {"code": "057", "name": "Zenith Bank"},
    {"code": "999991", "name": "OPay"},
    {"code": "999992", "name": "PalmPay"},
    {"code": "999993", "name": "Moniepoint Microfinance Bank"},
    {"code": "999994", "name": "Kuda Bank"},
    {"code": "999995", "name": "VFD Microfinance Bank"},
    {"code": "999996", "name": "Titan Trust Bank"},
    {"code": "999997", "name": "Jaiz Bank"},
    {"code": "999998", "name": "TAJBank"},
    {"code": "999999", "name": "Globus Bank"},
    {"code": "090267", "name": "Coronation Merchant Bank"},
  
]