# Generated by Django 5.2.5 on 2026-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akawo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akawomember',
            name='has_paid_first_contribution',
            field=models.BooleanField(default=False),
        ),
    ]
