# Generated by Django 5.2.5 on 2026-07-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akawo', '0002_akawomember_has_paid_first_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='akawogroup',
            name='current_receiver_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
