# Generated by Django 5.2.5 on 2026-07-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akawo', '0003_akawogroup_current_receiver_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='akawogroup',
            name='current_cycle',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
