# Generated by Django 5.2.5 on 2026-07-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akawo', '0004_akawogroup_current_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akawocontribution',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='akawocontribution',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='akawocontribution',
            name='status',
        ),
    ]
