# Generated by Django 5.2.5 on 2026-07-02 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akawo', '0005_remove_akawocontribution_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akawocontribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akawocontribution',
            name='cycle_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='akawocontribution',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='akawocontribution',
            name='status',
            field=models.CharField(default='successful', max_length=20),
        ),
    ]
