# Generated by Django 5.2.5 on 2026-07-27 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_created_at_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=10),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('rc_number', models.CharField(blank=True, help_text='CAC Registration Number', max_length=50)),
                ('business_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('limited_liability', 'Limited Liability Company'), ('partnership', 'Partnership'), ('ngo', 'NGO/Non-Profit'), ('other', 'Other')], default='sole_proprietorship', max_length=30)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('business_address', models.CharField(blank=True, max_length=255)),
                ('tin_number', models.CharField(blank=True, help_text='Tax Identification Number', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
