# Generated by Django 5.2.5 on 2026-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='nickname',
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
