# Generated by Django 5.2.5 on 2026-06-25 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_beneficiary_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_pin',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='nickname',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
