# Generated by Django 5.2.5 on 2026-06-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_wallet_account_number_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
