# Generated by Django 5.2.5 on 2026-06-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_wallet_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('airtime', 'Airtime'), ('data', 'Data'), ('card', 'Card'), ('bill', 'Bill Payment')], max_length=10),
        ),
    ]
