# Generated by Django 5.2.5 on 2026-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_wallet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
