# Generated by Django 5.2.5 on 2026-08-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_wallet_failed_pin_attempts_wallet_pin_locked_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_pin',
        ),
    ]
