# Generated by Django 5.2.5 on 2026-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_pendingwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=10),
        ),
        migrations.AddField(
            model_name='pendingwithdrawal',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='savings', max_length=10),
        ),
    ]
